# Generated by Django 4.2.1 on 2023-08-12 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_documenttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documenttype',
            old_name='documentName',
            new_name='documentTypeName',
        ),
    ]
