# Generated by Django 4.2.1 on 2023-08-12 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared', '0004_rename_documentname_documenttype_documenttypename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsystemCode', models.CharField(max_length=50)),
                ('subsystemName', models.CharField(max_length=200)),
                ('isActive', models.BooleanField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_Subsystem_2created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_Subsystem_2modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
