# Generated by Django 4.2.1 on 2023-08-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0005_subsystem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
