# Generated by Django 4.2.1 on 2023-08-17 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractCode', models.CharField(max_length=50)),
                ('contractName', models.CharField(max_length=200)),
                ('contractVersion', models.CharField(max_length=20)),
                ('contractType', models.CharField(max_length=200)),
                ('contractSize', models.FloatField()),
                ('contractBase64str', models.FileField(upload_to='')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('contractCustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Contract_Customer_2_contracCustomer', to='customer.customer')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_Contract_2created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_Contract_2modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
