# Generated by Django 4.2.3 on 2023-08-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_contract_contractbase64str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contractBase64str',
            field=models.TextField(blank=True),
        ),
    ]
